/motion_capture_tracking:
  ros__parameters:
    type: "optitrack"
    hostname: "130.149.82.37"

    mode: "libobjecttracker" # one of motionCapture,libRigidBodyTracker

    topics:
      poses:
        qos:
          mode: "none"
          deadline: 100.0 # Hz

    marker_configurations:
      default: # for standard Crazyflie
        offset: [0.0, 0.0, -0.04]
        points:
          p0: [0.03, 0.0, 0.0] # front
          p1: [0.00, -0.03, 0.0] # right
          p2: [-0.015, 0.0, 0.0] # back
          #p3: [0.00, 0.03, 0.0] # left
      default_single_marker:
        offset: [0.0, 0.0, -0.04]
        points:
          p0: [0.0177184,0.0139654,0.0557585]
      medium_frame:
        offset: [0.0, 0.0, -0.03]
        points:
          p0: [0.03, 0.0, 0.0] # front
          p1: [0.00, -0.03, 0.0] # right
          p2: [-0.015, 0.0, 0.0] # back
          p3: [0.00, 0.03, 0.0] # left
      big_frame:
        offset: [0.0, 0.0, -0.06]
        points:
          p0: [0.03, 0.0, 0.0] # front
          p1: [0.00, -0.03, 0.0] # right
          p2: [-0.015, 0.0, 0.0] # back
          p3: [0.00, 0.03, 0.0] # left

    dynamics_configurations:
      default:
        max_velocity: [2, 2, 3] # m/s
        max_angular_velocity: [20, 20, 10] # rad/s
        max_roll: 1.4 #rad
        max_pitch: 1.4 #rad
        max_fitness_score: 0.001

    rigid_bodies:
      crazyflie:
        initial_position: [0,0,0]
        marker: "default"
        dynamics: "default"